<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__a-o5absajr3fsk</name>
   <tag></tag>
   <elementGuidId>a18d416d-22a5-49e2-b4dd-fe21bd03985e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-o5absajr3fsk&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-o5absajr3fsk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-o5absajr3fsk&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9653d37f-c025-4f62-8fc0-2b67acda6b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>db92aafa-affb-431e-87ba-c48e3880b707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>e0583d36-44b2-461b-83dd-e8d39575e232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>bd857a0b-cbb4-4384-9d8d-3ff7437ee301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1a7f2670-071b-4ae5-a0f2-322c96ea69cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-o5absajr3fsk</value>
      <webElementGuid>3068bbfc-8a46-409d-944c-484ee6aa92ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>137b8452-afce-4b3a-9756-e07a533daf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>01e077de-bd98-4465-a56f-115fc6f4ea62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>a907dff4-0c6d-4804-8e83-f1256c1105bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=ko&amp;v=hbAq-YhJxOnlU-7cpgBoAJHb&amp;size=normal&amp;s=h75m_8TJj2CUSzmAEj4c0LROpGiyHFAGQvzA9_TlFfZ5qOsvao8jSs1EmmWWe5Aug2UXFuTGEv__2LfLtdbXfU_DQtH30aqEeWuevuJjUolqRRhUPBIuoQAGFxzH_1XBPdv8jb0AvJZOk1zw_7-WPqkL9UI-Npx2mvQh3yuQr0wMbvcKV0gnNliVvO6xE8U2kmrlIcYL5V6O9QSVOtr0sYedN6DBseaA652aUndZF-_igqRCPtfxvx6iMNYSQ1zJUPGYYwZyv8Iy7KVOEbPC0FAlViHNJ7M&amp;cb=a99rhnw6h24m</value>
      <webElementGuid>b3879cc4-f480-43f4-ad3a-7c24b8066150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>27dae142-2ed8-4cae-b186-1938b9292801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-o5absajr3fsk']</value>
      <webElementGuid>01d34817-ee8e-4329-a594-6544be6d4600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='recaptcha']/div/div/iframe</value>
      <webElementGuid>c79fa3fb-c76b-4ef7-8895-05adaea15c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0eed213a-6b49-466c-a5c5-ba18aee80eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-o5absajr3fsk' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b&amp;co=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbTo0NDM.&amp;hl=ko&amp;v=hbAq-YhJxOnlU-7cpgBoAJHb&amp;size=normal&amp;s=h75m_8TJj2CUSzmAEj4c0LROpGiyHFAGQvzA9_TlFfZ5qOsvao8jSs1EmmWWe5Aug2UXFuTGEv__2LfLtdbXfU_DQtH30aqEeWuevuJjUolqRRhUPBIuoQAGFxzH_1XBPdv8jb0AvJZOk1zw_7-WPqkL9UI-Npx2mvQh3yuQr0wMbvcKV0gnNliVvO6xE8U2kmrlIcYL5V6O9QSVOtr0sYedN6DBseaA652aUndZF-_igqRCPtfxvx6iMNYSQ1zJUPGYYwZyv8Iy7KVOEbPC0FAlViHNJ7M&amp;cb=a99rhnw6h24m']</value>
      <webElementGuid>7e89ade8-cd8e-4cf3-a496-f8e5511ec993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
