<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>dc825aaf-6039-437d-a6fa-8cedbd845d89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>814e44e5-62a4-4872-a1e7-fe6eec1248ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>3e71f6c5-b7d6-4991-b755-5c00b010b6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7xZ_My9XMwMHeMUFoo1uRi1iKq_Z5if2q0Q5eJY6-gk6iW3r8VRotOzgyKXKiKp6JYS_sexyl5hDSOSXwXoUdu9MVe0H7VFIuNq3ArB69i9MXLUgB95DSW45_NUzSrnZT9gjlW1F5ZCA8eDm5bme_Yl2clSiewM56ZUlm8GkVYKr9bWGGXbNWxJ1PPpD8SpB2Q_XD3&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b</value>
      <webElementGuid>7ca4acd1-3fe2-446c-96bb-e166e4b00304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>f1307561-7ae4-4b8d-88eb-9b64fc30b2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_httpswww.google.co.krsearchqECB9B4ED83_dadf9c/iframe_html1body1div2div4iframe1_c-o5absajr3fsk</value>
      <webElementGuid>7f5a29a8-a500-469b-a964-1a90f6ee9f9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>b3b3270b-c54f-4fdb-92db-730ba29af962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7xZ_My9XMwMHeMUFoo1uRi1iKq_Z5if2q0Q5eJY6-gk6iW3r8VRotOzgyKXKiKp6JYS_sexyl5hDSOSXwXoUdu9MVe0H7VFIuNq3ArB69i9MXLUgB95DSW45_NUzSrnZT9gjlW1F5ZCA8eDm5bme_Yl2clSiewM56ZUlm8GkVYKr9bWGGXbNWxJ1PPpD8SpB2Q_XD3&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b')])[5]</value>
      <webElementGuid>185f6958-1f7d-4552-8133-eb8ea4fc1b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>f11be920-89e3-4630-9840-b89c873f87e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7xZ_My9XMwMHeMUFoo1uRi1iKq_Z5if2q0Q5eJY6-gk6iW3r8VRotOzgyKXKiKp6JYS_sexyl5hDSOSXwXoUdu9MVe0H7VFIuNq3ArB69i9MXLUgB95DSW45_NUzSrnZT9gjlW1F5ZCA8eDm5bme_Yl2clSiewM56ZUlm8GkVYKr9bWGGXbNWxJ1PPpD8SpB2Q_XD3&amp;k=6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b']</value>
      <webElementGuid>d7ec6988-20ca-47ae-a888-7d69a15f09c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
