<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>3bf47f1e-a047-44f4-aaca-8f6d3a2a9666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.txt-button.login-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;GA_Event('공통_PC', 'gnb', '로그인');&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;로그인&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4bf75513-c522-441e-8498-87d58cda218f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Login/Login_Tot.asp?rDBName=GG&amp;re_url=/</value>
      <webElementGuid>e606cb18-4c21-4566-98dd-7458b6d95925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt-button login-button</value>
      <webElementGuid>6666a12e-eed6-4fe7-b8ba-c48b5f790594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>GA_Event('공통_PC', 'gnb', '로그인');</value>
      <webElementGuid>7c36e3df-30e5-4c5a-a486-cb0ed71af79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로그인</value>
      <webElementGuid>f87ae014-3b6e-4a6a-af9e-6f54afbead3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;devMyPage&quot;)/ul[@class=&quot;userNav&quot;]/li[@class=&quot;userNav-item login open&quot;]/a[@class=&quot;txt-button login-button&quot;]</value>
      <webElementGuid>ff691128-90f2-4287-bb9e-0f98a571539a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;GA_Event('공통_PC', 'gnb', '로그인');&quot;]</value>
      <webElementGuid>4f241a2e-dfd7-4517-8780-a6cc68de74fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='devMyPage']/ul/li/a</value>
      <webElementGuid>9646359a-6b24-475c-8c6a-520b83e1ed1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'로그인')]</value>
      <webElementGuid>82ddaf64-ee87-4281-9842-2dce6e91b05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취업톡톡'])[1]/following::a[1]</value>
      <webElementGuid>445a7bc2-1d45-464f-acf6-d117eebc9610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='커리어'])[1]/following::a[2]</value>
      <webElementGuid>805b9a20-c8a3-49df-a154-5b712ea8b526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='회원가입'])[1]/preceding::a[1]</value>
      <webElementGuid>66c0ac47-ac5d-4861-8754-3ea8b141b000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기업서비스'])[1]/preceding::a[2]</value>
      <webElementGuid>f8c26e32-8eb9-48f3-8ef9-1154b840df24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='로그인']/parent::*</value>
      <webElementGuid>e6ca5fee-ea95-44f4-8faf-bb28a748607e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Login/Login_Tot.asp?rDBName=GG&amp;re_url=/')]</value>
      <webElementGuid>9f152f23-6a69-4478-95fa-fa3c30b453f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/ul/li/a</value>
      <webElementGuid>7968866a-dc4a-48fe-992e-f86e538d9533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Login/Login_Tot.asp?rDBName=GG&amp;re_url=/' and (text() = '로그인' or . = '로그인')]</value>
      <webElementGuid>999b8c5b-eb0c-4e40-ab7b-0fcc57c68347</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
