<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__M_PWD</name>
   <tag></tag>
   <elementGuidId>70eeedc4-4997-4213-b056-9ad9be7d5706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#M_PWD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M_PWD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;비밀번호&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fcf3ca0-2a2e-444d-889b-4899d4cac3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>226b9de5-0d47-44b3-8a28-d1858d2a312d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inpTxt input-password</value>
      <webElementGuid>9015bbd1-719a-43a8-a564-361762d6f88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>비밀번호</value>
      <webElementGuid>2e422738-366d-4aaf-ba7a-7a42cd8eeab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>M_PWD</value>
      <webElementGuid>d20eb2f2-6e4c-42c8-b2e4-0ddd163b4d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M_PWD</value>
      <webElementGuid>5e5584dd-a436-4489-bd19-9078e310161b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>748d7ffc-7bdd-484b-88fe-b57ec7e7f571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>비밀번호 입력</value>
      <webElementGuid>b1eb83a9-ccd3-4537-9e16-437d5ffd06fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M_PWD&quot;)</value>
      <webElementGuid>98c3ddd9-85fa-4be2-b86c-e155304cc393</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M_PWD']</value>
      <webElementGuid>b98b6d8c-9779-4b1f-8f89-e2361d5a7fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/fieldset/section[3]/input[2]</value>
      <webElementGuid>b0078452-9c33-4688-bfb1-7bf12298442c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/input[2]</value>
      <webElementGuid>1ad0fba4-e540-4248-be4a-19d872d8998b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = '비밀번호' and @name = 'M_PWD' and @id = 'M_PWD' and @title = '비밀번호 입력']</value>
      <webElementGuid>cc37934a-da84-438e-9aa2-15bfdced0200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
