<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NO.1   ID_M_ID</name>
   <tag></tag>
   <elementGuidId>b3092c15-5d0b-4c75-81b4-7cdac39db67f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#M_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;NO.1 잡코리아·알바몬 통합 ID&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4db1924-386a-47ed-a4a8-48a74dd30542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08767006-1fb2-4e76-b019-206c2274ba1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inpTxt  input-id</value>
      <webElementGuid>98a49172-adf2-4e3d-a738-cec2d2eeedce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NO.1 잡코리아·알바몬 통합 ID</value>
      <webElementGuid>bc39c4d2-6217-4036-9b33-2f28ac03f568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>M_ID</value>
      <webElementGuid>9dd1d0a2-223e-45ab-9fff-fce3a36eaed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M_ID</value>
      <webElementGuid>373e7b21-a686-472a-99a9-61c0b31e6df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>e1e95466-38ad-445f-9461-fe06ef71644d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>bc381520-830e-434e-ab1f-9ecc96e0b337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>아이디 입력</value>
      <webElementGuid>d4a4da89-1741-4cec-9e51-1429adfe2d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M_ID&quot;)</value>
      <webElementGuid>ff5491f9-ab89-4c5b-a006-421d4fa16ada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M_ID']</value>
      <webElementGuid>2472a253-67c5-4521-a317-ed524ef29128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/fieldset/section[3]/input</value>
      <webElementGuid>09445cca-cd9a-435d-ad76-ccef7cc9ec07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/input</value>
      <webElementGuid>0be1d921-c9b9-41d7-bfe1-650b380ed462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'NO.1 잡코리아·알바몬 통합 ID' and @name = 'M_ID' and @id = 'M_ID' and @title = '아이디 입력']</value>
      <webElementGuid>718ea474-3281-4c4f-9ea4-e0e32af5c133</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
